apiVersion: kruize.io/v1alpha1
kind: Kruize
metadata:
  labels:
    app.kubernetes.io/name: kruize-operator
    app.kubernetes.io/managed-by: kustomize
  name: kruize-sample
spec:
  # Supported values: "openshift", "minikube", "kind"
  cluster_type: "kind"
  size: 3
  autotune_image: "quay.io/rh-ee-shesaxen/autotune:optimizerPoCDemo"
  autotune_ui_image: "quay.io/rh-ee-shesaxen/kruize-ui:optimizerPoCDemo"
  optimizer_image: "quay.io/rh-ee-shesaxen/optimizer:optimizerPoCDemo"
  non_interactive: 1
  use_yaml_build: 0	
  autotune_configmaps: "autotune-configmaps"
  # For OpenShift, use: "openshift-tuning", Minikube/KIND, use: "monitoring"
  namespace: "monitoring"